print("Museums are very important places. Museums are of all kinds. Some are big , small , curtural , informative and:")
print("historic. Many of us visit these museums to study and learn the past . There are even other types of museums")
print("like space museums and plant museums(bio museums). I to have gone to a museum once.")
print("")
print("During my trip in London my parents took me to the Science museum of England. When I entered the building I saw")
print("some giant models of some space shuttles with the idols of famous astrounauts like the great Neil Amstrong and")
print("Edward Buzz Aldrin , the first people to go to the moon. It had felt as if Ihad entered the land of intelligenc")
print("-e and the land of history of the dimension of space. In the space sector the second thing I saw were small,")
print("colourful, clean, and mesmerizing models of space plants(so called in sience fiction) which were a totally diff")
print("erent species. The next thing I saw was a marvellous, almost life_like , colourful(only orange stripes(uneven))")
print(",it was a model asteroid . In this museum i felt all my unawnesered quentions about space and some of its origi")
print("ns were slowly becoming answered. Next came the NASA sector where there were hundreds of models of past, presen")
print("t, and future models of space aircrafts . It was amazing to see the big model of the apollo aircraft and NASAs")
print("first satellite, some of the concepts were also very good . The element testing lab was also fun. We had the li")
print("berty to mix any two or three or infite elements together to make infinite combinations.")
print("")
print("This was a very  fun trip to the Science museum of England and I also respect the people who built answer some ")
print("unanswered quetion in our mind.")
print("I will never forget this experience.")
print("Please enter marks upon 20")
n = int(input())
if(n >= 13):
    print("Yay!")
else:
    print("Boo!")

