print("During 2020 India faced a virus attack. The name given to the virus was covid 19. The government had to force us")
print("to stay at home in hope that it would stop the spread. This period is called the lockdown. During the lockdown m")
print("any of us developed certain talents and did many extra curricular activities that involve learning, speech and.")
print("drama and so on.")
print("")
print("During the lockdown my average day  consisted of studying in the morning  and the rest of the day enhancing my")
print("talents. During the lockdown some of the exquisite talents that I learned were art, craft, and computer")
print("programming. The first talent I learned was art. On Sundays when I was bored seeing my father_s anarchy and ")
print("action movies, I sat down and did my art in a pleasent and tranquil environment and did my art by emotiona")
print("lly drawing therby soothing the heart and the soul. Another exquiste talent I learnt was craft. Many craft spec")
print("ialist say that craft is the language of intelligent minds. I learnt craft in order to master creativity.")
print("I have also learnt that craft is more than just putting glue between two pieces of paper but to use your creati")
print("vity to make something out of it. So in reality I do agree with the specialists that art really is the language")
print("of an intelligent mind.The next talent was computer programming . This was my favourite since it took me two mo")
print("nths to learn. The idea of writing code in order to create a program fascinates me. ")
print("")
print("These are the talents I learnt in the lockdown. I hope you learned some to. I will keep enhancing each of these")
print("talents until I am a master in them.")
print("Thank you")
print("Please enter marks")
n = int(input())
if(n>=13):
    print("yay")
else:
    print("boo, This is the essay of a non-creative man")